# encoding: utf-8
from constants import *
#角色信息界面
LABEL_NAME_CONTENT = "Guild name:"
LABEL_NAME_POSITION = (MAP_SIZE[0] + 20, 10)

LABEL_GOLD_CONTENT = "      Gold:"
LABEL_GOLD_POSITION = (LABEL_NAME_POSITION[0], LABEL_NAME_POSITION[1] + 20)

LABEL_WOOD_CONTENT = "      Wood:"
LABEL_WOOD_POSITION = (LABEL_NAME_POSITION[0], LABEL_NAME_POSITION[1] + 40)

LABEL_BRICK_CONTENT = "      Brick:"
LABEL_BRICK_POSITION = (LABEL_NAME_POSITION[0], LABEL_NAME_POSITION[1] + 60)

LABEL_IRON_CONTENT = "      Iron:"
LABEL_IRON_POSITION = (LABEL_NAME_POSITION[0], LABEL_NAME_POSITION[1] + 80)

LABEL_SHEEP_CONTENT = "      Sheep:"
LABEL_SHEEP_POSITION = (LABEL_NAME_POSITION[0], LABEL_NAME_POSITION[1] + 100)

LABEL_SCORE_CONTENT = "      Score:"
LABEL_SCORE_POSITION = (LABEL_NAME_POSITION[0], LABEL_NAME_POSITION[1] + 120)
